### ISSUE TITLE
include from D2 readme

### ISSUE THREAD

**Issue by alixander** [meinside/telegram-d2-bot#1]
hey @meinside , this looks great! if it's ready, i'm happy to link from the main D2 readme/site if it's okay with you

**Comment by meinside** [comment]
Wow, that would be an honor for me!
I was looking for a good library for converting .svg files to image files, but no success so far due to the embeded font files. So it is still WIP, but if that's okay, please feel free to do so. :-)

**Comment by alixander** [comment]
we do support png exports now in the latest version, perhaps you could give that a try and let me know if it works?

**Comment by meinside** [comment]
Oh, that's a good news! I'll try it ASAP.

**Comment by meinside** [comment]
Now it responses with .png files (using Playwright)!
